class DepoHareketleri {
  int id;
  int fisId;
  int kartTuruId;
  int depoHareketYonuId;
  int depoHareketTipiId;
  double birim1Miktari;
  double birim2Miktari;
  String aciklama;
  int stokId;
  int depoId;
  int depoKoridorId;
  DateTime createdDate;
  DateTime modifiedDate;
  int depoRafId;
  int barkodId;
  int masrafYeriId;
  DateTime tarih;
  int siparisDetayId;
  int aktif;
  int isDeleted;
  int connectedRowId;
  int refDbTableId;
  int refDetayId;
  int karsiDepoId;
  int seferTakipId;
  int gonderimKontrol;
  int isSend;
  int bobinSyncStatus;

  DepoHareketleri({
    required this.id,
    required this.fisId,
    required this.kartTuruId,
    required this.depoHareketYonuId,
    required this.depoHareketTipiId,
    required this.birim1Miktari,
    required this.birim2Miktari,
    required this.aciklama,
    required this.stokId,
    required this.depoId,
    required this.depoKoridorId,
    required this.createdDate,
    required this.modifiedDate,
    required this.depoRafId,
    required this.barkodId,
    required this.masrafYeriId,
    required this.tarih,
    required this.siparisDetayId,
    required this.aktif,
    required this.isDeleted,
    required this.connectedRowId,
    required this.refDbTableId,
    required this.refDetayId,
    required this.karsiDepoId,
    required this.seferTakipId,
    required this.gonderimKontrol,
    required this.isSend,
    required this.bobinSyncStatus,
  });

  factory DepoHareketleri.fromJson(Map<String, dynamic> json) => DepoHareketleri(
    id: json['Id'],
    fisId: json['FisId'],
    kartTuruId: json['KartTuruId'],
    depoHareketYonuId: json['DepoHareketYonuId'],
    depoHareketTipiId: json['DepoHareketTipiId'],
    birim1Miktari: json['Birim1Miktari'],
    birim2Miktari: json['Birim2Miktari'],
    aciklama: json['Aciklama'],
    stokId: json['StokId'],
    depoId: json['DepoId'],
    depoKoridorId: json['DepoKoridorId'],
    createdDate: DateTime.parse(json['CreatedDate']),
    modifiedDate: DateTime.parse(json['ModifiedDate']),
    depoRafId: json['DepoRafId'],
    barkodId: json['BarkodId'],
    masrafYeriId: json['MasrafYeriId'],
    tarih: DateTime.parse(json['Tarih']),
    siparisDetayId: json['SiparisDetayId'],
    aktif: json['Aktif'],
    isDeleted: json['IsDeleted'],
    connectedRowId: json['ConnectedRowId'],
    refDbTableId: json['RefDbTableId'],
    refDetayId: json['RefDetayId'],
    karsiDepoId: json['KarsiDepoId'],
    seferTakipId: json['SeferTakipId'],
    gonderimKontrol: json['GonderimKontrol'],
    isSend: json['IsSend'],
    bobinSyncStatus: json['BobinSyncStatus'],
  );

  Map<String, dynamic> toJson() => {
    'Id': id,
    'FisId': fisId,
    'KartTuruId': kartTuruId,
    'DepoHareketYonuId': depoHareketYonuId,
    'DepoHareketTipiId': depoHareketTipiId,
    'Birim1Miktari': birim1Miktari,
    'Birim2Miktari': birim2Miktari,
    'Aciklama': aciklama,
    'StokId': stokId,
    'DepoId': depoId,
    'DepoKoridorId': depoKoridorId,
    'CreatedDate': createdDate.toIso8601String(),
    'ModifiedDate': modifiedDate.toIso8601String(),
    'DepoRafId': depoRafId,
    'BarkodId': barkodId,
    'MasrafYeriId': masrafYeriId,
    'Tarih': tarih.toIso8601String(),
    'SiparisDetayId': siparisDetayId,
    'Aktif': aktif,
    'IsDeleted': isDeleted,
    'ConnectedRowId': connectedRowId,
    'RefDbTableId': refDbTableId,
    'RefDetayId': refDetayId,
    'KarsiDepoId': karsiDepoId,
    'SeferTakipId': seferTakipId,
    'GonderimKontrol': gonderimKontrol,
    'IsSend': isSend,
    'BobinSyncStatus': bobinSyncStatus,
  };
}
